# Generated by Django 5.2.11 on 2026-03-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_description_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttransaction',
            name='product',
        ),
        migrations.AddField(
            model_name='transaction',
            name='revenue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
