# Generated by Django 5.2.11 on 2026-03-30 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_producttransaction_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
