# Generated by Django 5.2.11 on 2026-03-30 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_producttransaction_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
